### ISSUE TITLE
Multiplication table is expected

### ISSUE THREAD

**Issue by asarfraaz** [Basavarajkembhavimath/python_exc#1]
The existing code prints only the multiples of 17 and not the multiplication table of 17

https://github.com/Basavarajkembhavimath/python_exc/blob/6ba6df70778248f70a10dc3e8ff5060dd8bf0705/multipliction.py

The expected output is :

17 x 1 = 17
17 x 2 = 34
17 x 3 = 51
... and so on

**Comment by Basavarajkembhavimath** [comment]
updated the code
