### ISSUE TITLE
Update code to get multiplication table

### ISSUE THREAD

**Issue by asarfraaz** [Basavarajkembhavimath/python_exc#2]
https://github.com/Basavarajkembhavimath/python_exc/blob/6ba6df70778248f70a10dc3e8ff5060dd8bf0705/multiplication_any_no.py

For an input as 5, the expected output is : 

5 x 1 =   5
5 x 2 = 10
5 x 3 = 15
... and so on

**Comment by Basavarajkembhavimath** [comment]
yes sir I updated the code
